### ISSUE TITLE
Erfolgreich in Contao 4.4 getestet, Bitte um Freigabe

### ISSUE THREAD

**Issue by lebleucleu** [cliffparnitzky/TinyMceAnchor#1]
Eine manuelle Installation in Contao 4.4 ist möglich. Ich hatte dazu einfach die Verzeichnisse, die für eine manuelle Installation in Contao 3.5 vorgesehen waren, hier eingefügt:
/assets/tinymce4/js/plugins/anchor
/system/modules/TinyMceAnchor
Nachdem der Contao-Cache via Contao Manager neu erstellt wurde, ist Anchor in Front- und Backend verfügbar.
Danke und Grüße
Klaus

**Comment by cliffparnitzky** [comment]
Viele Dank für den Test.

Diese Änderungen bedürfen leider etwas Aufwand. Insofern kann ich keine Zeit für die Umsetzung angeben.

**Comment by cliffparnitzky** [comment]
Detail infos for update: https://gist.github.com/cliffparnitzky/f5693c4bcf756ee73e8bdc2a5d37aa3a

**Comment by lebleucleu** [comment]
Thanks for the update!!

**Comment by cliffparnitzky** [comment]
Implemented in b0a29baf62651ac85664f283856b9b3ab2b03907
